// Validation
const MIN_CANVAS_WIDTH = 1
const MIN_CANVAS_HEIGHT = 1
const MIN_COL_WIDTH = 1
const MIN_COLS = 1
const MIN_MARGIN = 0
const MIN_GRID_WIDTH = 1
const MIN_GUTTER_WIDTH = 0
module.exports.MIN_CANVAS_WIDTH = MIN_CANVAS_WIDTH
module.exports.MIN_CANVAS_HEIGHT = MIN_CANVAS_HEIGHT
module.exports.MIN_COL_WIDTH = MIN_COL_WIDTH
module.exports.MIN_COLS = MIN_COLS
module.exports.MIN_MARGIN = MIN_MARGIN
module.exports.MIN_GRID_WIDTH = MIN_GRID_WIDTH
module.exports.MIN_GUTTER_WIDTH = MIN_GUTTER_WIDTH

// GridCalcError
const GRID_CALC_ERROR_TYPE_CRITICAL = 'critical'
const GRID_CALC_ERROR_TYPE_SILENT = 'silent'
module.exports.GRID_CALC_ERROR_TYPE_CRITICAL = GRID_CALC_ERROR_TYPE_CRITICAL
module.exports.GRID_CALC_ERROR_TYPE_SILENT = GRID_CALC_ERROR_TYPE_SILENT
